print("Hello, world!")
print("My name is Alex.")
print("I love playing football. ")
print("The result of 3 + 5 is:", 3 + 5 )
print("The result of 3 * 5 is:", 3 * 5)
print("The result of 3 - 5 is:", 3 - 5)
print("The result of 3 / 5 is:", 3 / 5)
print("My name is Maheeb.")
print("I love playing football. ")
print("I also enjoy watching Formula One races.")
print("I like reading books.")